version: '3.8'

networks:
  monitoring-net:
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: devops-app
    ports:
      - "8000:8000"
    networks:
      - monitoring-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: devops-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.0
    container_name: devops-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net
    restart: unless-stopped