apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
  namespace: devops-lab
spec:
  replicas: 1 # 1 réplica é suficiente para o lab em nó único
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          # Usando uma imagem pública leve para validar a comunicação no GKE
          image: nginxdemos/hello:plain-text
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"