apiVersion: v1
kind: Service
metadata:
  name: devops-app-lb
  namespace: devops-lab
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80