apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: devops-lab
spec:
  type: ClusterIP # IP virtual estático visível apenas dentro do cluster
  selector:
    app: devops-app # Encamina o tráfego para os Pods que possuem a label app: devops-app
  ports:
    - protocol: TCP
      port: 80 # Porta exposta pelo Service
      targetPort: 8000 # Porta onde o container da API escuta